# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/d800-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/d800-common/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/lge/d800-common/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/lge/d800-common/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/lge/d800-common/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/lge/d800-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/lge/d800-common/proprietary/bin/efsks:system/bin/efsks \
    vendor/lge/d800-common/proprietary/bin/ks:system/bin/ks \
    vendor/lge/d800-common/proprietary/bin/mm-audio-ftm:system/bin/mm-audio-ftm \
    vendor/lge/d800-common/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lge/d800-common/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/d800-common/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/d800-common/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/lge/d800-common/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/lge/d800-common/proprietary/bin/qcks:system/bin/qcks \
    vendor/lge/d800-common/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/d800-common/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/lge/d800-common/proprietary/bin/radish:system/bin/radish \
    vendor/lge/d800-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/d800-common/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/lge/d800-common/proprietary/bin/thermald:system/bin/thermald \
    vendor/lge/d800-common/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/lge/d800-common/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/lge/d800-common/proprietary/etc/diag.cfg:system/etc/diag.cfg \
    vendor/lge/d800-common/proprietary/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    vendor/lge/d800-common/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/lge/d800-common/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/lge/d800-common/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/lge/d800-common/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/lge/d800-common/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/lge/d800-common/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/lge/d800-common/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/lge/d800-common/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/lge/d800-common/proprietary/etc/firmware/fw_bcmdhd_mfg.bin:system/etc/firmware/fw_bcmdhd_mfg.bin \
    vendor/lge/d800-common/proprietary/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \
    vendor/lge/d800-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/lge/d800-common/proprietary/etc/firmware/wcd9320/wcd9320_anc.bin:system/etc/firmware/wcd9320/wcd9320_anc.bin \
    vendor/lge/d800-common/proprietary/etc/firmware/wcd9320/wcd9320_mbhc.bin:system/etc/firmware/wcd9320/wcd9320_mbhc.bin \
    vendor/lge/d800-common/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
    vendor/lge/d800-common/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/d800-common/proprietary/lib/egl/libEGL_adreno.so:system/lib/egl/libEGL_adreno.so \
    vendor/lge/d800-common/proprietary/lib/egl/libGLESv1_CM_adreno.so:system/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lge/d800-common/proprietary/lib/egl/ibGLESv2_adreno.so:system/lib/egl/ibGLESv2_adreno.so \
    vendor/lge/d800-common/proprietary/lib/egl/libq3dtools_adreno.so:system/lib/egl/libq3dtools_adreno.so \
    vendor/lge/d800-common/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/lge/d800-common/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/lge/d800-common/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/lge/d800-common/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/d800-common/proprietary/lib/libAKM8963.so:system/lib/libAKM8963.so \
    vendor/lge/d800-common/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/lge/d800-common/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/lge/d800-common/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/lge/d800-common/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
    vendor/lge/d800-common/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/lge/d800-common/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/lge/d800-common/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/lge/d800-common/proprietary/lib/libcamera_fast_af.so:system/lib/libcamera_fast_af.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx132_common.so:system/lib/libchromatix_imx132_common.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx132_default_video.so:system/lib/libchromatix_imx132_default_video.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx132_mms_video.so:system/lib/libchromatix_imx132_mms_video.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx132_preview.so:system/lib/libchromatix_imx132_preview.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx132_vt.so:system/lib/libchromatix_imx132_vt.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_common.so:system/lib/libchromatix_imx135_common.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_default_video.so:system/lib/libchromatix_imx135_default_video.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_hfr_60.so:system/lib/libchromatix_imx135_hfr_60.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_mms_video.so:system/lib/libchromatix_imx135_mms_video.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_preview.so:system/lib/libchromatix_imx135_preview.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_snapshot.so:system/lib/libchromatix_imx135_snapshot.so \
    vendor/lge/d800-common/proprietary/lib/libchromatix_imx135_video_dualrec.so:system/lib/libchromatix_imx135_video_dualrec.so \
    vendor/lge/d800-common/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/lge/d800-common/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/lge/d800-common/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/lge/d800-common/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/d800-common/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/lge/d800-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/lge/d800-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/lge/d800-common/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/d800-common/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/lge/d800-common/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/d800-common/proprietary/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
    vendor/lge/d800-common/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/lge/d800-common/proprietary/lib/libHDR.so:system/lib/libHDR.so \
    vendor/lge/d800-common/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/lge/d800-common/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/d800-common/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/lge/d800-common/proprietary/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
    vendor/lge/d800-common/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_c2d_module.so:system/lib/libmmcamera2_c2d_module.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_cpp_module.so:system/lib/libmmcamera2_cpp_module.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_iface_modules.so:system/lib/libmmcamera2_iface_modules.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_imglib_modules.so:system/lib/libmmcamera2_imglib_modules.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_isp_modules.so:system/lib/libmmcamera2_isp_modules.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_pproc_modules.so:system/lib/libmmcamera2_pproc_modules.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_sensor_modules.so:system/lib/libmmcamera2_sensor_modules.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_stats_algorithm..so:system/lib/libmmcamera2_stats_algorithm..so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_stats_modules.so:system/lib/libmmcamera2_stats_modules.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_vpe_module.so:system/lib/libmmcamera2_vpe_module.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera2_wnr_module.so:system/lib/libmmcamera2_wnr_module.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_imx132.so:system/lib/libmmcamera_imx132.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_imx135.so:system/lib/libmmcamera_imx135.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_imx135_eeprom.so:system/lib/libmmcamera_imx135_eeprom.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/lge/d800-common/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/d800-common/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/d800-common/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/d800-common/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/lge/d800-common/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/lge/d800-common/proprietary/lib/libmorpho_image_stab31.so:system/lib/libmorpho_image_stab31.so \
    vendor/lge/d800-common/proprietary/lib/libmorpho_noise_reduction.so:system/lib/libmorpho_noise_reduction.so \
    vendor/lge/d800-common/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/d800-common/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/d800-common/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/lge/d800-common/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/lge/d800-common/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/lge/d800-common/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/lge/d800-common/proprietary/lib/libproxyhal.so:system/lib/libproxyhal.so \
    vendor/lge/d800-common/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/lge/d800-common/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/d800-common/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/d800-common/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/d800-common/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/d800-common/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/lge/d800-common/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/lge/d800-common/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/lge/d800-common/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/lge/d800-common/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/lge/d800-common/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/lge/d800-common/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/lge/d800-common/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/d800-common/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/d800-common/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/d800-common/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/lge/d800-common/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/lge/d800-common/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/lge/d800-common/proprietary/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
    vendor/lge/d800-common/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/lge/d800-common/proprietary/vendor/firmware/BCM20791B4_002.005.010.0098.0000_Generic_I2CNVM1NOUICC1_NCD_Signed_configdata.ncd:system/vendor/firmware/BCM20791B4_002.005.010.0098.0000_Generic_I2CNVM1NOUICC1_NCD_Signed_configdata.ncd \
    vendor/lge/d800-common/proprietary/vendor/firmware/BCM20791B4_002.005.010.0098.0000_Generic_PreI2C_NCD_Signed_configdata.ncd:system/vendor/firmware/BCM20791B4_002.005.010.0098.0000_Generic_PreI2C_NCD_Signed_configdata.ncd \
    vendor/lge/d800-common/proprietary/vendor/firmware/BCM20791B5_002.006.013.0011.0003_LGE_P6_A1_I2C_NCD_Signed_configdata.ncd:system/vendor/firmware/BCM20791B5_002.006.013.0011.0003_LGE_P6_A1_I2C_NCD_Signed_configdata.ncd \
    vendor/lge/d800-common/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/lge/d800-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/lge/d800-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/lge/d800-common/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/lge/d800-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so
